"""empty message

Revision ID: 4329e44c4c87
Revises: ffdc0a98111c
Create Date: 2021-07-19 14:23:36.319971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4329e44c4c87'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('dog_total_distance', sa.Integer(), nullable=True),
    sa.Column('dog_total_walks', sa.Integer(), nullable=True),
    sa.Column('dog_total_duration', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=False))
    op.add_column('users', sa.Column('image_url', sa.String()))
    op.add_column('users', sa.Column('user_total_distance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_total_walks', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_total_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_total_duration')
    op.drop_column('users', 'user_total_walks')
    op.drop_column('users', 'user_total_distance')
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'name')
    op.drop_table('dogs')
    # ### end Alembic commands ###
