"""create date as date type

Revision ID: 6b6554badb88
Revises: 336d64d8f3e8
Create Date: 2021-07-22 14:20:07.240888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6554badb88'
down_revision = '336d64d8f3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walks', 'date')
    # ### end Alembic commands ###
