"""empty message

Revision ID: 22a078d639ef
Revises: 4329e44c4c87
Create Date: 2021-07-20 16:45:47.097646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a078d639ef'
down_revision = '4329e44c4c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('routeData', sa.PickleType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogwalks',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ),
    sa.PrimaryKeyConstraint('dog_id', 'walk_id')
    )
    op.alter_column('users', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('dogwalks')
    op.drop_table('walks')
    # ### end Alembic commands ###
