"""remove date column from walks

Revision ID: 336d64d8f3e8
Revises: 22a078d639ef
Create Date: 2021-07-22 14:17:43.706934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '336d64d8f3e8'
down_revision = '22a078d639ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('walks', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('dogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
